import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
   'client',
  ],
  tutorial: [
    {
      type: 'autogenerated',
      dirName: 'tutorial'
    },
  ],
  zeus_q: [
    
      {
        type: 'category',
        label: '魔云腾主机的介绍与使用',
        items: [
          'zeus-q/魔云腾主机介绍',
          'zeus-q/安装指南',
          'zeus-q/ubuntu使用',
          
        ],
      },
    
      {
        type: 'category',
        label: '开发',
        items: [
          'zeus-q/按需制定文件系统',
            {
              type: 'category',
              label: '应用案例',
              items: [
                'zeus-q/运行rkllm大模型',
                'zeus-q/运行rknn demo',
                'zeus-q/运行rkmpp demo',
                'zeus-q/安装librga库',
                'zeus-q/运行jellyfin',

              ],
            },
        ],
      },
      'zeus-q/维护与保养',
      'zeus-q/常见问题',
      'zeus-q/安全信息',
      'zeus-q/保修服务政策',
  ],
  kehuduan:[
    {
      type: 'category',
      label: '客户端使用说明',
      items: [
        'kehuduan/PC客户端',
        'kehuduan/带屏幕机型操作',
        
        
      ],
    },
  ]
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
