import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
   'client',
  ],
  tutorial: [
    {
      type: 'autogenerated',
      dirName: 'tutorial'
    },
  ],
  MYTOS开发教程:[
    'MYTOS/通用常规问题介绍',    
    'MYTOS/SSH连接',
    'MYTOS/格式化固态硬盘',
    'MYTOS/设备助手使用注意规范',
    'MYTOS/手动配置网络参数',
    'MYTOS/数据安全备份及迁移',
    'MYTOS/清理未使用的安卓镜像',
    'MYTOS/按需制定文件系统',
    
    {
      type: 'category',
      label: '开发',
      items: [
        
          {
            type: 'category',
            label: '应用案例',
            items: [
              'MYTOS/运行rkllm大模型',
              'MYTOS/运行rknn demo',
              'MYTOS/运行rkmpp demo',
              'MYTOS/安装librga库',
              'MYTOS/运行jellyfin',

            ],
          },
      ],
    },
  ],
  zeus_q: [
    
      {
        type: 'category',
        label: 'Q1主机的介绍与使用',
        items: [
          'zeus-q/Q1主机介绍',
          'zeus-q/MYT Zeus Q1 主机固件',
          'zeus-q/ubuntu使用',
          'zeus-q/安装指南',
        ],
      },
      'zeus-q/维护与保养',
      'zeus-q/常见问题',
      'zeus-q/安全信息',
      'zeus-q/保修服务政策',
  ],
  kehuduan:[

    {
      type: 'category',
      label: 'PC客户端使用说明',
      items: [
        'kehuduan/PC客户端',
        'kehuduan/带屏幕机型操作',
        'kehuduan/安全模式',
        'kehuduan/正确设置安卓DNS',        
      ],
    },
    {
      type: 'category',
      label: 'WEB客户端使用说明',
      items: [
        'kehuduan/Myt Zues C1-VPC网络管理',
               
      ],
    },
  ]
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
